apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-gateway.fullname" . }}-config
  labels:
    {{- include "llm-gateway.labels" . | nindent 4 }}
data:
  guardrail.config.yaml: |
{{ .Values.runtimeConfig | indent 4 }}
  main.yaml: |
{{ .Values.policy | indent 4 }}
